language: java

before_install:
 - chmod +x gradlew

after_success:
  - ./gradlew jacocoTestReport
  - pip install --user codecov
  - codecov 
  
  
 # checkstyle (oraclejdk8)
  - jdk: oraclejdk8
      env:
        - DESC="checkstyle and sevntu-checkstyle"
        - CMD="export MAVEN_OPTS='-Xmx2000m' && mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
